// Inputs
global.set("SLIDER_OVERTRAVEL_N", I0[0]);
global.set("SLIDER_OVERTRAVEL_P", I0[1]);
global.set("TRANSFER_ARM_LIMIT", I0[2]);
global.set("ROTARY_HOME_POS", I0[3]);
global.set("TRANSFER_ARM_POS", I0[4]);
global.set("START_BTN", I0[8]);
global.set("STOP_BTN", I0[9]);
global.set("HOME_BTN", I0[10]);
global.set("ROBOT_BUSY_STATUS", I0[11]);
global.set("MAT_INPUT_DETECTED", I0[12]);
global.set("MAT_HEIGHT_CHECKED", I0[13]);
global.set("MAT_2_SORT_DETECTED", I8[0]);
global.set("MAT_SCRAP_DETECTED", I8[1]);
global.set("RFID_SELECT_MAT_1", I8[2]);
global.set("RFID_SELECT_MAT_2", I8[3]);
global.set("PRESSURE_LOW", I8[4]);
global.set("MAT_1_LOADING_DONE", I8[5]);
global.set("MAT_2_LOADING_DONE", I8[6]);
global.set("MAT_2_PUSHOUT_DONE", I8[7]);
global.set("ROTARY_PICKING_REACH", I12[1]);
global.set("Z_CYLINDER_RETRACT_POS", I12[2]);
global.set("Z_CYLINDER_EXTEND_POS", I12[3]);
global.set("X_CYLINDER_RETRACT_POS", I12[4]);
global.set("X_CLINDER_EXTEND_POS", I12[5]);
global.set("MAT_BASE_LOADING_REACH", I12[6]);
global.set("MAT_TOP_LOADING_REACH", I12[7]);
global.set("ABS_VACUUM_SUCTION_REACH", I16[0]);
global.set("VISION_CHECK_PASS", I16[1]);
global.set("VISION_CHECK_FAIL", I16[2]);

// Outputs
global.set("EN_GANTRY_SLIDER_AXIS", Q0[1]);
global.set("DIR_ROTARY_TABLE", Q0[2]);
global.set("EN_ROTARY_TABLE", Q0[3]);
global.set("DIR_TRANSFER_ARM", Q0[4]);
global.set("EN_TRANSFER_ARM", Q0[5]);
global.set("CONVEYOR_M1_ON", Q0[6]);
global.set("CONVEYOR_M2_ON", Q0[7]);
global.set("MOTOR_DRILLING_ON", Q0[8]);
global.set("ALARM_LIGHT_RED", Q0[9]);
global.set("MAT_IN_2_SOL_ON", Q12[0]);
global.set("MAT_OUT_2_SOL_ON", Q12[1]);
global.set("CLAMPING_ARM", Q12[2]);
global.set("Z_CYLINDER_SOL_ON", Q12[3]);
global.set("X_CYLINDER_SOL_ON", Q12[4]);
global.set("Y_CYLINDER_SOL_ON", Q12[5]);
global.set("ROTARY_SLIDER", Q12[6]);
global.set("BASE_CUP_MAT_LOADING_LEVEL", Q12[7]);
global.set("BASE_CUP_MAT_PUSH_OUT", Q16[0]);
global.set("TOP_CUP_MAT_LOADING_LEVEL", Q16[1]);
global.set("TOP_CUP_MAT_PUSH_OUT", Q16[2]);
global.set("ENABLE_VACUUM_SUCTION", Q16[3]);
global.set("PWM_GantrySlider", Q4[0]);
global.set("PWM_RotaryTable", Q4[1]);
global.set("PWM_TransferArm", Q4[2]);
global.set("DIR_GANTRY_SLIDER_AXIS", Q4[3]);
global.set("CYCLESTOP_LIGHT_YELLOW", Q8[0]);
global.set("CYCLESTART_LIGHT_GREEN", Q8[1]);
global.set("ROBOT_ARM_RUN_ACKNOWLEDGE", Q8[2]);
global.set("ROBOT_MODE_SEL_BIT0", Q8[3]);
global.set("ROBOT_MODE_SEL_BIT1", Q8[4]);
global.set("ROBOT_MODE_SEL_BIT2", Q8[5]);
global.set("READY_FOR_VISION_INSPECTION", Q8[6]);
global.set("MAT_IN_1_SOL_ON", Q8[7]);

// Registers

global.set("ACTIVATE_CONVEYOR_RIGHT_SEQ", bit_test(M10, 0));
global.set("MAT_2_SORT_REACHED", bit_test(M10, 1));
global.set("MAT_2_SORT_BEGIN", bit_test(M10, 2));
global.set("MAT__SCRAP_DETECT", bit_test(M10, 3));
global.set("MAT_SCRAP_COUNTED", bit_test(M10, 4));
global.set("CONV_RIGHT_RUN", bit_test(M10, 5));
global.set("CONV_RIGHT_READY_FOR_PICKUP", bit_test(M10, 6));
global.set("START_LEFT_CONVEYOR", bit_test(M100, 0));
global.set("START_ROBOT_ARM_ACTION", bit_test(M100, 1));
global.set("START_DRILLING", bit_test(M100, 2));
global.set("START_CONVEYOR_RIGHT", bit_test(M100, 3));
global.set("START_LOAD_BASE_PART", bit_test(M100, 4));
global.set("RUN_ROTATRY_TABLE", bit_test(M100, 5));
global.set("START_TRANSFER_ARM", bit_test(M100, 6));
global.set("START_VISION_CAMERA", bit_test(M100, 7));
global.set("MOVE_TO_TOP_PART_POS", bit_test(M101, 0));
global.set("START_LOAD_TOP_PART", bit_test(M101, 1));
global.set("START_CALL_PICKING_POS", bit_test(M101, 2));
global.set("START_PICKING", bit_test(M101, 3));
global.set("START_STORAGE", bit_test(M101, 4));
global.set("START_STORAGE_UNLOAD", bit_test(M101, 5));
global.set("END_OF_CYCLE", bit_test(M101, 6));
global.set("RUN_ROBOT_ARM", bit_test(M11, 0));
global.set("ENABLE_ACTION_GROUP_11", bit_test(M11, 1));
global.set("ENABLE_ACTION_GROUP_12", bit_test(M11, 2));
global.set("ENABLE_ACTION_GROUP_13", bit_test(M11, 3));
global.set("ROBOT_ACTION_PROGRAM_ENDED", bit_test(M11, 4));
global.set("PLC_READY", bit_test(M11, 5));
global.set("GS_HOME_RUN", bit_test(M12, 0));
global.set("GS_HOMING_TIME_EXCEED", bit_test(M12, 1));
global.set("RUN_POCKET_PICKING_FROM_LEFT", bit_test(M13, 0));
global.set("RUN_POCKET_1", bit_test(M13, 1));
global.set("RUN_POCKET_2", bit_test(M13, 2));
global.set("RUN_POCKET_3", bit_test(M13, 3));
global.set("RUN_POCKET_4", bit_test(M13, 4));
global.set("RUN_POCKET_5", bit_test(M13, 5));
global.set("RUN_POCKET_PICKING_TO_RIGHT", bit_test(M13, 7));
global.set("RT_HOME_RUN", bit_test(M14, 0));
global.set("RT_HOME_TIME_EXCEED", bit_test(M14, 1));
global.set("RT_HOME_PULSE_DETECTED", bit_test(M14, 4));
global.set("RT_HOME_CCW", bit_test(M14, 5));
global.set("RT_HOME_CW", bit_test(M14, 6));
global.set("TA_HOME_RUN", bit_test(M16, 0));
global.set("TA_HOMING_TIME_EXCEED", bit_test(M16, 1));
global.set("TA_HOME_PULSE_DETECTED", bit_test(M16, 4));
global.set("TA_HOME_CCW", bit_test(M16, 5));
global.set("TA_HOME_CW", bit_test(M16, 6));
global.set("ACTIVATE_TA_PICKING_SEQ", bit_test(M17, 0));
global.set("TA_DIRECTION_CCW", bit_test(M17, 1));
global.set("TA_PICKING_TIME_EXCEED", bit_test(M17, 3));
global.set("ACTIVATE_TA_UNLOAD_SEQ", bit_test(M17, 4));
global.set("TA_DIRECTION_CW", bit_test(M17, 5));
global.set("Enable_Vacuum_Pick", bit_test(M17, 2));
global.set("Disable_Vacuum_Pick", bit_test(M17, 6));
global.set("TA_UNLOAD_TIME_EXCEED", bit_test(M17, 7));
global.set("ACTIVATE_ROTARY_TABLE_SEQ", bit_test(M18, 0));
global.set("GANTRY_DriveEnable", bit_test(M2, 0));
global.set("ROTARY_TABLE_DriveEnable", bit_test(M2, 1));
global.set("TRANSFER_ARM_DriveEnable", bit_test(M2, 2));
global.set("GS_HOMED", bit_test(M200, 0));
global.set("GS_HOMED_ERROR", bit_test(M200, 1));
global.set("RT_HOMED", bit_test(M200, 2));
global.set("RT_HOMED_ERROR", bit_test(M200, 3));
global.set("TA_HOMED", bit_test(M200, 4));
global.set("TA_HOMED_ERROR", bit_test(M200, 5));
global.set("READY_TO_RUN", bit_test(M200, 7));
global.set("ONE_CYCLE", bit_test(M201, 0));
global.set("AUTO_CYCLE", bit_test(M201, 1));
global.set("PB_START_NEG", bit_test(M201, 2));
global.set("MAT_TRAY_SELECTED", bit_test(M201, 3));
global.set("CONV_LEFT_TRIGGER", bit_test(M201, 4));
global.set("ROBOT_ARM_DONE_TRIGGER", bit_test(M201, 5));
global.set("CONV_RIGHT_TRIGGER", bit_test(M201, 6));
global.set("LOADING_BASE_DONE_TRIGGER", bit_test(M201, 7));
global.set("RT_MOVE_DONE_TRIGGER", bit_test(M202, 0));
global.set("TA_PICKING_FUNC_DONE_TRIG", bit_test(M202, 1));
global.set("TA_UNLOAD_FUNC_DONE_TRIG", bit_test(M202, 2));
global.set("GS_STORAGE_POCKET_DONE", bit_test(M202, 3));
global.set("GS_RUN_PICKING_DONE_TRIGGER", bit_test(M202, 4));
global.set("GS_STORAGE_POCKET_DONE_TRIGGER", bit_test(M202, 5));
global.set("EMERGENCY_STOP", bit_test(M203, 0));
global.set("EMERGENCY_STOP_TRIGGER", bit_test(M203, 1));
global.set("HOME_RESET_TRIGGER", bit_test(M203, 2));
global.set("CONV_LEFT_ERROR_TRIGGER", bit_test(M204, 0));
global.set("CONV_LEFT_BUSY", bit_test(M300, 0));
global.set("ROBOT_ARM_BUSY", bit_test(M300, 1));
global.set("CONV_RIGHT_BUSY", bit_test(M300, 2));
global.set("DRILLING_BUSY", bit_test(M300, 3));
global.set("LOAD_BASE_BUSY", bit_test(M300, 4));
global.set("ROTARY_TABLE_BUSY", bit_test(M300, 5));
global.set("TA_BUSY", bit_test(M300, 6));
global.set("VISION_BUSY", bit_test(M300, 7));
global.set("LOAD_TOP_BUSY", bit_test(M301, 0));
global.set("PICK_STOR_BUSY", bit_test(M301, 1));
global.set("UNLOAD_TO_UPPER_LVL", bit_test(M4, 0));
global.set("UNLOAD_TO_BOTTOM_LVL", bit_test(M4, 1));
global.set("CLAMPING_ARM_RELEASED", bit_test(M4, 2));
global.set("ZY_TURN_ON", bit_test(M4, 3));
global.set("X_CYLINDER_RETRACT", bit_test(M4, 4));
global.set("Z_CYLINDER_RETRACT", bit_test(M4, 5));
global.set("END_UPPER_UNLOAD_SEQUENCE", bit_test(M4, 6));
global.set("END_BOTTOM_UNLOAD_SEQUENCE", bit_test(M4, 7));
global.set("LEFT_TO_PICKING_POS", bit_test(M5, 0));
global.set("PICKING_POS_TO_RIGHT", bit_test(M5, 1));
global.set("GS_RUN_PICKING", bit_test(M5, 2));
global.set("GS_RUN_STORAGE", bit_test(M5, 3));
global.set("UPPER_LEVEL_STORAGE", bit_test(M5, 4));
global.set("BOTTOM_LEVEL_STORAGE", bit_test(M5, 5));
global.set("GS_RUN_STORAGE_BEGIN", bit_test(M5, 6));
global.set("GS_RUN_PICKING_BEGIN", bit_test(M5, 7));
global.set("LOADING_TOP_CUP", bit_test(M6, 0));
global.set("MAT_TOP_REACH_TRIGGER", bit_test(M6, 1));
global.set("TOP_PUSHOUT", bit_test(M6, 2));
global.set("WAIT_TOP_RETRACT", bit_test(M6, 3));
global.set("LOADING_TOP_COMPLETED", bit_test(M6, 4));
global.set("LOADING_TOP_DONE_TRIGGER", bit_test(M6, 5));
global.set("LOAD_TOP_DONE", bit_test(M6, 6));
global.set("Y_CYLINDER_TURN_ON", bit_test(M6, 7));
global.set("START_TRANSFER_ARM_UNLOAD", bit_test(M7, 2));
global.set("TA_SEQ_Completed", bit_test(M7, 4));
global.set("VISION_CHECK_PASS", bit_test(M7, 5));
global.set("VISION_CHECK_FAIL", bit_test(M7, 6));
global.set("VISION_CHECK_Fault", bit_test(M7, 7));
global.set("DRILLING_PROCESS_END", bit_test(M8, 0));
global.set("LOADING_BASE_CUP", bit_test(M8, 1));
global.set("MAT_BASE_REACH_TRIGGER", bit_test(M8, 2));
global.set("BASE_PUSHOUT", bit_test(M8, 3));
global.set("WAIT_RETRACT", bit_test(M8, 4));
global.set("LOADING_BASE_COMPLETED", bit_test(M8, 5));
global.set("LOAD_BASE_DONE", bit_test(M8, 6));
global.set("ACTIVATE_CONVEYOR_LEFT_SEQ", bit_test(M9, 0));
global.set("LOAD_M1", bit_test(M9, 1));
global.set("LOAD_M2", bit_test(M9, 2));
global.set("CONV_LEFT_RUN", bit_test(M9, 3));
global.set("MAT_HEIGHT_PASS", bit_test(M9, 4));
global.set("MAT_HEIGHT_DETECTED", bit_test(M9, 5));
global.set("MAT_INPUT_READY_FOR_PICKUP", bit_test(M9, 6));
global.set("MAT_PROCESS_TO_SCRAP", bit_test(M9, 7));

return msg;
