msg.topic = "telemetry";

var holdReg = global.get("holdReg");

msg.payload = {
  ROTARY_HOME_POS: global.get("ROTARY_HOME_POS") ? 1 : 0,
  TRANSFER_ARM_POS: global.get("TRANSFER_ARM_POS") ? 1 : 0,
  ROBOT_BUSY_STATUS: global.get("ROBOT_BUSY_STATUS") ? 1 : 0,
  MAT_INPUT_DETECTED: global.get("MAT_INPUT_DETECTED") ? 1 : 0,
  MAT_SCRAP_DETECTED: global.get("MAT_SCRAP_DETECTED") ? 1 : 0,
  RFID_SELECT_MAT_1: global.get("RFID_SELECT_MAT_1") ? 1 : 0,
  RFID_SELECT_MAT_2: global.get("RFID_SELECT_MAT_2") ? 1 : 0,
  PRESSURE_LOW: global.get("PRESSURE_LOW") ? 1 : 0,
  MAT_1_LOADING_DONE: global.get("MAT_1_LOADING_DONE") ? 1 : 0,
  MAT_2_LOADING_DONE: global.get("MAT_2_LOADING_DONE") ? 1 : 0,
  VISION_CHECK_PASS: global.get("VISION_CHECK_PASS") ? 1 : 0,
  VISION_CHECK_FAIL: global.get("VISION_CHECK_FAIL") ? 1 : 0,
  EN_GANTRY_SLIDER_AXIS: global.get("EN_GANTRY_SLIDER_AXIS") ? 1 : 0,
  EN_ROTARY_TABLE: global.get("EN_ROTARY_TABLE") ? 1 : 0,
  EN_TRANSFER_ARM: global.get("EN_TRANSFER_ARM") ? 1 : 0,
  CONVEYOR_M1_ON: global.get("CONVEYOR_M1_ON") ? 1 : 0,
  CONVEYOR_M2_ON: global.get("CONVEYOR_M2_ON") ? 1 : 0,
  MOTOR_DRILLING_ON: global.get("MOTOR_DRILLING_ON") ? 1 : 0,
  ALARM_LIGHT_RED: global.get("ALARM_LIGHT_RED") ? 1 : 0,
  CLAMPING_ARM: global.get("CLAMPING_ARM") ? 1 : 0,
  ROTARY_SLIDER: global.get("ROTARY_SLIDER") ? 1 : 0,
  ENABLE_VACUUM_SUCTION: global.get("ENABLE_VACUUM_SUCTION") ? 1 : 0,
  CYCLESTOP_LIGHT_YELLOW: global.get("CYCLESTOP_LIGHT_YELLOW") ? 1 : 0,
  CYCLESTART_LIGHT_GREEN: global.get("CYCLESTART_LIGHT_GREEN") ? 1 : 0,
  READY_FOR_VISION_INSPECTION: global.get("READY_FOR_VISION_INSPECTION")
    ? 1
    : 0,
  MAT_SCRAP_COUNTED: global.get("MAT_SCRAP_COUNTED") ? 1 : 0,
  CONV_RIGHT_READY_FOR_PICKUP: global.get("CONV_RIGHT_READY_FOR_PICKUP")
    ? 1
    : 0,
  START_DRILLING: global.get("START_DRILLING") ? 1 : 0,
  START_CONVEYOR_RIGHT: global.get("START_CONVEYOR_RIGHT") ? 1 : 0,
  START_LOAD_BASE_PART: global.get("START_LOAD_BASE_PART") ? 1 : 0,
  RUN_ROTATRY_TABLE: global.get("RUN_ROTATRY_TABLE") ? 1 : 0,
  START_TRANSFER_ARM: global.get("START_TRANSFER_ARM") ? 1 : 0,
  START_VISION_CAMERA: global.get("START_VISION_CAMERA") ? 1 : 0,
  MOVE_TO_TOP_PART_POS: global.get("MOVE_TO_TOP_PART_POS") ? 1 : 0,
  START_LOAD_TOP_PART: global.get("START_LOAD_TOP_PART") ? 1 : 0,
  START_CALL_PICKING_POS: global.get("START_CALL_PICKING_POS") ? 1 : 0,
  START_PICKING: global.get("START_PICKING") ? 1 : 0,
  START_STORAGE: global.get("START_STORAGE") ? 1 : 0,
  START_STORAGE_UNLOAD: global.get("START_STORAGE_UNLOAD") ? 1 : 0,
  END_OF_CYCLE: global.get("END_OF_CYCLE") ? 1 : 0,
  RUN_ROBOT_ARM: global.get("RUN_ROBOT_ARM") ? 1 : 0,
  PLC_READY: global.get("PLC_READY") ? 1 : 0,
  GS_HOME_RUN: global.get("GS_HOME_RUN") ? 1 : 0,
  GS_HOMING_TIME_EXCEED: global.get("GS_HOMING_TIME_EXCEED") ? 1 : 0,
  RT_HOME_RUN: global.get("RT_HOME_RUN") ? 1 : 0,
  RT_HOME_TIME_EXCEED: global.get("RT_HOME_TIME_EXCEED") ? 1 : 0,
  TA_HOME_RUN: global.get("TA_HOME_RUN") ? 1 : 0,
  TA_HOMING_TIME_EXCEED: global.get("TA_HOMING_TIME_EXCEED") ? 1 : 0,
  ACTIVATE_TA_PICKING_SEQ: global.get("ACTIVATE_TA_PICKING_SEQ") ? 1 : 0,
  TA_DIRECTION_CCW: global.get("TA_DIRECTION_CCW") ? 1 : 0,
  TA_PICKING_TIME_EXCEED: global.get("TA_PICKING_TIME_EXCEED") ? 1 : 0,
  ACTIVATE_TA_UNLOAD_SEQ: global.get("ACTIVATE_TA_UNLOAD_SEQ") ? 1 : 0,
  TA_DIRECTION_CW: global.get("TA_DIRECTION_CW") ? 1 : 0,
  TA_UNLOAD_TIME_EXCEED: global.get("TA_UNLOAD_TIME_EXCEED") ? 1 : 0,
  READY_TO_RUN: global.get("READY_TO_RUN") ? 1 : 0,
  ONE_CYCLE: global.get("ONE_CYCLE") ? 1 : 0,
  AUTO_CYCLE: global.get("AUTO_CYCLE") ? 1 : 0,
  EMERGENCY_STOP: global.get("EMERGENCY_STOP") ? 1 : 0,
  CONV_LEFT_BUSY: global.get("CONV_LEFT_BUSY") ? 1 : 0,
  ROBOT_ARM_BUSY: global.get("ROBOT_ARM_BUSY") ? 1 : 0,
  CONV_RIGHT_BUSY: global.get("CONV_RIGHT_BUSY") ? 1 : 0,
  DRILLING_BUSY: global.get("DRILLING_BUSY") ? 1 : 0,
  LOAD_BASE_BUSY: global.get("LOAD_BASE_BUSY") ? 1 : 0,
  ROTARY_TABLE_BUSY: global.get("ROTARY_TABLE_BUSY") ? 1 : 0,
  TA_BUSY: global.get("TA_BUSY") ? 1 : 0,
  VISION_BUSY: global.get("VISION_BUSY") ? 1 : 0,
  LOAD_TOP_BUSY: global.get("LOAD_TOP_BUSY") ? 1 : 0,
  UNLOAD_TO_UPPER_LVL: global.get("UNLOAD_TO_UPPER_LVL") ? 1 : 0,
  UNLOAD_TO_BOTTOM_LVL: global.get("UNLOAD_TO_BOTTOM_LVL") ? 1 : 0,
  CLAMPING_ARM_RELEASED: global.get("CLAMPING_ARM_RELEASED") ? 1 : 0,
  END_UPPER_UNLOAD_SEQUENCE: global.get("END_UPPER_UNLOAD_SEQUENCE") ? 1 : 0,
  END_BOTTOM_UNLOAD_SEQUENCE: global.get("END_BOTTOM_UNLOAD_SEQUENCE") ? 1 : 0,
  GS_RUN_PICKING: global.get("GS_RUN_PICKING") ? 1 : 0,
  GS_RUN_STORAGE: global.get("GS_RUN_STORAGE") ? 1 : 0,
  UPPER_LEVEL_STORAGE: global.get("UPPER_LEVEL_STORAGE") ? 1 : 0,
  BOTTOM_LEVEL_STORAGE: global.get("BOTTOM_LEVEL_STORAGE") ? 1 : 0,
  GS_RUN_STORAGE_BEGIN: global.get("GS_RUN_STORAGE_BEGIN") ? 1 : 0,
  GS_RUN_PICKING_BEGIN: global.get("GS_RUN_PICKING_BEGIN") ? 1 : 0,
  LOADING_TOP_CUP: global.get("LOADING_TOP_CUP") ? 1 : 0,
  LOAD_TOP_DONE: global.get("LOAD_TOP_DONE") ? 1 : 0,
  START_TRANSFER_ARM_UNLOAD: global.get("START_TRANSFER_ARM_UNLOAD") ? 1 : 0,
  TA_SEQ_Completed: global.get("TA_SEQ_Completed") ? 1 : 0,
  DRILLING_PROCESS_END: global.get("DRILLING_PROCESS_END") ? 1 : 0,
  LOADING_BASE_CUP: global.get("LOADING_BASE_CUP") ? 1 : 0,
  LOAD_BASE_DONE: global.get("LOAD_BASE_DONE") ? 1 : 0,
  MAT_PROCESS_TO_SCRAP: global.get("MAT_PROCESS_TO_SCRAP") ? 1 : 0,
  ERR_STATUS: holdReg[4],
};

return msg;
